version: "3.2"
services:
  rabbitmq:
    build: docker_tools/rabbitmq
    image: rabbitmq-mqtt
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883

  db:
    image: 'mariadb:10.3'
    container_name: db
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "mariadb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mariadb